name: yb-singlezone

networks:
  yb-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.42.0.0/16
          gateway: 10.42.0.1

x-common-master: &common-master
  image: docker.io/yugabytedb/yugabyte:2025.1.0.1-b3
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:7000"]
    interval: 5s
    timeout: 2s
    retries: 5

x-common-tserver:: &common-tserver
  image: docker.io/yugabytedb/yugabyte:2025.1.0.1-b3
  depends_on:
    ybmaster0:
      condition: service_healthy
    ybmaster1:
      condition: service_healthy
    ybmaster2:
      condition: service_healthy
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000"]
    interval: 5s
    timeout: 2s
    retries: 10

services:
  ybmaster0:
    <<: *common-master
    container_name: ybmaster0
    volumes:
      - ybmaster0:/data
    ports:
      - 7000:7000
    networks:
      yb-net:
        ipv4_address: 10.42.1.100
    command:
      - /home/yugabyte/bin/yb-master
      - --fs_data_dirs=/data
      - --replication-factor=3
      - --placement_cloud=local
      - --placement_region=local
      - --placement_zone=docker0
      - --ysql_num_shards_per_tserver=1
      - --webserver_interface=10.42.1.100
      - --rpc_bind_addresses=10.42.1.100
      - --master_addresses=10.42.1.100:7100,10.42.1.101:7100,10.42.1.102:7100

  ybmaster1:
    <<: *common-master
    container_name: ybmaster1
    volumes:
      - ybmaster1:/data
    ports:
      - 7001:7000
    networks:
      yb-net:
        ipv4_address: 10.42.1.101
    command:
      - /home/yugabyte/bin/yb-master
      - --fs_data_dirs=/data
      - --replication-factor=3
      - --placement_cloud=local
      - --placement_region=local
      - --placement_zone=docker0
      - --ysql_num_shards_per_tserver=1
      - --webserver_interface=10.42.1.101
      - --rpc_bind_addresses=10.42.1.101
      - --master_addresses=10.42.1.100:7100,10.42.1.101:7100,10.42.1.102:7100
  ybmaster2:
    <<: *common-master
    container_name: ybmaster2
    volumes:
      - ybmaster2:/data
    ports:
      - 7002:7000
    networks:
      yb-net:
        ipv4_address: 10.42.1.102
    command:
      - /home/yugabyte/bin/yb-master
      - --fs_data_dirs=/data
      - --replication-factor=3
      - --placement_cloud=local
      - --placement_region=local
      - --placement_zone=docker0
      - --ysql_num_shards_per_tserver=1
      - --webserver_interface=10.42.1.102
      - --rpc_bind_addresses=10.42.1.102
      - --master_addresses=10.42.1.100:7100,10.42.1.101:7100,10.42.1.102:7100

  ybtserver0:
    <<: *common-tserver
    container_name: ybtserver0
    volumes:
      - ybtserver0:/data
    ports:
      - 9000:9000
    networks:
      yb-net:
        ipv4_address: 10.42.1.200
    command:
      - /home/yugabyte/bin/yb-tserver
      - --fs_data_dirs=/data
      - --enable_ysql
      - --ysql_enable_auth=true
      - --ysql_pg_conf_csv=password_encryption=scram-sha-256
      -  --placement_cloud=local
      - --placement_region=local
      - --placement_zone=docker0
      - --ysql_num_shards_per_tserver=1
      - --webserver_interface=10.42.1.200
      - --rpc_bind_addresses=10.42.1.200
      - --tserver_master_addrs=10.42.1.100:7100,10.42.1.101:7100,10.42.1.102:7100

  ybtserver1:
    <<: *common-tserver
    container_name: ybtserver1
    volumes:
      - ybtserver1:/data
    ports:
      - 9001:9000
    networks:
      yb-net:
        ipv4_address: 10.42.1.201
    command:
      - /home/yugabyte/bin/yb-tserver
      - --fs_data_dirs=/data
      - --enable_ysql
      - --ysql_enable_auth=true
      - --ysql_pg_conf_csv=password_encryption=scram-sha-256
      -  --placement_cloud=local
      - --placement_region=local
      - --placement_zone=docker0
      - --ysql_num_shards_per_tserver=1
      - --webserver_interface=10.42.1.201
      - --rpc_bind_addresses=10.42.1.201
      - --tserver_master_addrs=10.42.1.100:7100,10.42.1.101:7100,10.42.1.102:7100

  ybtserver2:
    <<: *common-tserver
    container_name: ybtserver2
    volumes:
      - ybtserver2:/data
    ports:
      - 9002:9000
    networks:
      yb-net:
        ipv4_address: 10.42.1.202
    command:
      - /home/yugabyte/bin/yb-tserver
      - --fs_data_dirs=/data
      - --enable_ysql
      - --ysql_enable_auth=true
      - --ysql_pg_conf_csv=password_encryption=scram-sha-256
      -  --placement_cloud=local
      - --placement_region=local
      - --placement_zone=docker0
      - --ysql_num_shards_per_tserver=1
      - --webserver_interface=10.42.1.202
      - --rpc_bind_addresses=10.42.1.202
      - --tserver_master_addrs=10.42.1.100:7100,10.42.1.101:7100,10.42.1.102:7100

  yb-workload-simulator:
    image: yb-workfload-simulator
    restart: always
    container_name: yb-workload-simulator
    depends_on:
      ybtserver0:
        condition: service_healthy
    ports:
      - 8081:8080
    environment:
      JAVA_OPTS: -Dnode=10.42.1.200,10.42.1.201,10.42.1.202 -Ddbuser=workload -Ddbpassword=workload -Ddbname=workload
    networks:
      - yb-net

volumes:
  ybmaster0:
  ybmaster1:
  ybmaster2:
  ybtserver0:
  ybtserver1:
  ybtserver2:
